name: Build Vue
on:
  repository_dispatch:
  push:
    branches:
      - main

jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
    - uses: actions/checkout@v4
    - id: Build-Vue
      uses: xRealNeon/VuePagesAction@1.0.1
      with:
          username: "vrw-GH"
          reponame: "gotq-spa"
          token: ${{ secrets.GITHUB_TOKEN }}
    # - name: Use Node.js
    #   with:
    #      node-version: '18.x'    
    #   uses: actions/setup-node@v4
    # - run: yarn
    # - run: yarn run build
    # - name: Deploy
    #   uses: peaceiris/actions-gh-pages@v3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./build